# Unilink source and public header lists. Keep these explicit so packaging and
# IDE integration do not depend on globbing.

set(UNILINK_SOURCES
    unilink/transport/tcp_server/tcp_server.cc
    unilink/transport/tcp_client/tcp_client.cc
    unilink/transport/serial/serial.cc
    unilink/builder/auto_initializer.cc
    unilink/builder/serial_builder.cc
    unilink/builder/tcp_client_builder.cc
    unilink/builder/tcp_server_builder.cc
    unilink/builder/udp_builder.cc
    unilink/builder/unified_builder.cc
    unilink/concurrency/io_context_manager.cc
    unilink/config/config_factory.cc
    unilink/config/config_manager.cc
    unilink/diagnostics/error_handler.cc
    unilink/diagnostics/exceptions.cc
    unilink/diagnostics/logger.cc
    unilink/factory/channel_factory.cc
    unilink/interface/channel.cc
    unilink/interface/itcp_acceptor.cc
    unilink/interface/itcp_socket.cc
    unilink/memory/memory_pool.cc
    unilink/memory/memory_tracker.cc
    unilink/memory/safe_data_buffer.cc
    unilink/transport/tcp_server/boost_tcp_acceptor.cc
    unilink/transport/tcp_server/boost_tcp_socket.cc
    unilink/transport/tcp_server/tcp_server_session.cc
    unilink/transport/udp/udp.cc
    unilink/transport/uds/boost_uds_acceptor.cc
    unilink/transport/uds/boost_uds_socket.cc
    unilink/transport/uds/uds_client.cc
    unilink/transport/uds/uds_server.cc
    unilink/transport/uds/uds_server_session.cc
    unilink/util/input_validator.cc
    unilink/wrapper/serial/serial.cc
    unilink/wrapper/tcp_client/tcp_client.cc
    unilink/wrapper/tcp_server/tcp_server.cc
    unilink/wrapper/udp/udp.cc
    unilink/wrapper/udp/udp_server.cc
    unilink/wrapper/uds_client/uds_client.cc
    unilink/wrapper/uds_server/uds_server.cc
    unilink/builder/uds_builder.cc
    unilink/framer/line_framer.cc
    unilink/framer/packet_framer.cc
)

set(UNILINK_HEADERS
    unilink/base/common.hpp
    unilink/base/constants.hpp
    unilink/base/deprecated.hpp
    unilink/base/platform.hpp
    unilink/base/visibility.hpp
    unilink/framer/iframer.hpp
    unilink/framer/line_framer.hpp
    unilink/framer/packet_framer.hpp
    unilink/builder/auto_initializer.hpp
    unilink/builder/ibuilder.hpp
    unilink/builder/serial_builder.hpp
    unilink/builder/tcp_client_builder.hpp
    unilink/builder/tcp_server_builder.hpp
    unilink/builder/udp_builder.hpp
    unilink/builder/uds_builder.hpp
    unilink/builder/unified_builder.hpp
    unilink/concurrency/io_context_manager.hpp
    unilink/concurrency/thread_safe_state.hpp
    unilink/config/config_factory.hpp
    unilink/config/config_manager.hpp
    unilink/config/iconfig_manager.hpp
    unilink/config/serial_config.hpp
    unilink/config/tcp_client_config.hpp
    unilink/config/tcp_server_config.hpp
    unilink/config/udp_config.hpp
    unilink/config/uds_config.hpp
    unilink/diagnostics/error_handler.hpp
    unilink/diagnostics/error_types.hpp
    unilink/diagnostics/exceptions.hpp
    unilink/diagnostics/logger.hpp
    unilink/factory/channel_factory.hpp
    unilink/interface/channel.hpp
    unilink/interface/iserial_port.hpp
    unilink/interface/itcp_acceptor.hpp
    unilink/interface/itcp_resolver.hpp
    unilink/interface/itcp_socket.hpp
    unilink/interface/itimer.hpp
    unilink/interface/iuds_acceptor.hpp
    unilink/interface/iuds_socket.hpp
    unilink/memory/memory_pool.hpp
    unilink/memory/memory_tracker.hpp
    unilink/memory/memory_validator.hpp
    unilink/memory/safe_data_buffer.hpp
    unilink/memory/safe_span.hpp
    unilink/transport/serial/boost_serial_port.hpp
    unilink/transport/serial/serial.hpp
    unilink/transport/base/bp_utils.hpp
    unilink/transport/base/reconnect_policy.hpp
    unilink/transport/tcp_client/tcp_client.hpp
    unilink/transport/tcp_server/boost_tcp_acceptor.hpp
    unilink/transport/tcp_server/boost_tcp_socket.hpp
    unilink/transport/tcp_server/tcp_server_session.hpp
    unilink/transport/tcp_server/tcp_server.hpp
    unilink/transport/udp/udp.hpp
    unilink/transport/uds/boost_uds_acceptor.hpp
    unilink/transport/uds/boost_uds_socket.hpp
    unilink/transport/uds/uds_client.hpp
    unilink/transport/uds/uds_server.hpp
    unilink/transport/uds/uds_server_session.hpp
    unilink/unilink.hpp
    unilink/util/input_validator.hpp
    unilink/wrapper/ichannel.hpp
    unilink/wrapper/serial/serial.hpp
    unilink/wrapper/tcp_client/tcp_client.hpp
    unilink/wrapper/tcp_server/tcp_server.hpp
    unilink/wrapper/udp/udp.hpp
    unilink/wrapper/uds_client/uds_client.hpp
    unilink/wrapper/uds_server/uds_server.hpp
)
